builds:
  - env:
    - GO111MODULE=on
  - binary: vpngate-cli
    main: ./cmd/vpngate-cli
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X main.version={{ .Version }}
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: saihon
    name: vpngate-cli